# Generated by Django 5.2.1 on 2025-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Message', models.CharField(max_length=200)),
                ('ReminderType', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=20)),
            ],
        ),
    ]
