# Generated by Django 5.2.1 on 2025-05-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReminderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='ReminderType',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], default='SMS', max_length=20),
        ),
    ]
